### ISSUE TITLE
pre-commit integration

### ISSUE THREAD

**Issue by rhoitjadhav** [petrgazarov/FastAPI-app#1]
I think, having the pre-commit would be a great value to the project. Might create a PR for this soon.

Ref: https://pre-commit.com/

**Comment by petrgazarov** [comment]
Thanks for opening this issue! Are there specific hooks you are thinking of?

**Comment by rhoitjadhav** [comment]
I think the following can be added in the repo, however there are other hooks that can be added in future as per the requirements.

1. Black code formatter
2. end of line fixer
3. trailing white spaces
4. Add license header (if required)

You can refer to [this](https://pre-commit.com/hooks.html) for more hooks

Please let me know your thoughts so that I can work on that.

**Comment by petrgazarov** [comment]
The first three sound great, thanks!

1. Black code formatter
2. end of line fixer
3. trailing white spaces

**Comment by rhoitjadhav** [comment]
Created PR #2 and let me know if it requires any changes.
