### ISSUE TITLE
snake_case to camelCase for every responses from server to client

### ISSUE THREAD

**Issue by rhoitjadhav** [petrgazarov/FastAPI-app#3]
What happens is whenever we create models in FastAPI we create the variables in snake_case as per the PEP-8 standard, however in the frontend it requires camel-case  fields. To solve this issue we should use Pydantic Aliases. Please refer [this](https://stackoverflow.com/a/67995890/7755797) for more info.

**Comment by petrgazarov** [comment]
This is indeed a problem I had to solve with my frontend. I used openapi-typescript-codegen package with [some modifications](https://github.com/ferdikoomen/openapi-typescript-codegen/pull/1465#issuecomment-1519194808).

If aliases are used, what does that do to the OpenAPI schema - does it convert the docs into camel case?

**Comment by rhoitjadhav** [comment]
Yes it does convert to camel case. You can use vice versa in case you want came to snake case.
See the example below:

```python
from pydantic import BaseModel


def snake_to_camel(snake_str):
    words = snake_str.split("_")

    return words[0] + "".join(word.title() for word in words[1:])


class Model(BaseModel):
    first_name: str
    last_name: str

    class Config:
        alias_generator = snake_to_camel


from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root(model: Model):
    return {"message": "Hello World"}

```

![image](https://github.com/petrgazarov/FastAPI-app/assets/25402160/f0cb3a87-c490-49cb-986a-1757dc75960c)

**Comment by petrgazarov** [comment]
Thanks for suggesting this idea!

I believe the casing for the API should not be client-specific. It's better for the separation of concerns. It's also common to have multiple types of clients (web, mobile, server), and not all of them use camel case. I would leave it to the frontend to handle the conversion from `CamelCase` -> `snake_case` before sending the request.
