### ISSUE TITLE
Unable to run make migrate due to pydantic errors

### ISSUE THREAD

**Issue by dannykellett** [petrgazarov/FastAPI-app#4]
(venv) PS E:\11-Projects\FastAPI-app> make migrate
alembic upgrade head
E:\11-Projects\FastAPI-app\venv\Lib\site-packages\pydantic\_internal\_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
  warnings.warn(message, UserWarning)
...
...
  File "E:\11-Projects\FastAPI-app\venv\Lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.6/migration/#basesettings-has-
moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.6/u/import-error
make: *** [Makefile:24: migrate] Error 1

**Comment by petrgazarov** [comment]
Thanks for opening the issue. Pydantic lib now defaults to V2, and there are breaking API changes. I would accept a pull request that either upgrades to V2, or at least locks the version to V1.
